import vertexai
from vertexai import agent_engines
from google.adk.agents import LlmAgent
from app.agent_builder.tools import create_gitlab_mcp_toolset
from app.config import settings
import logging

logger = logging.getLogger(__name__)


# Agent System Prompt (Instruction)
SYNKRON_INSTRUCTION = """
You are Synkron, an autonomous documentation maintenance agent.

Your job: When a developer pushes code to GitLab, analyze what changed
and update only the documentation files that need to reflect that change.

## Your Workflow

1. **Read the diff** — Call get_commit_diff with the project_id and commit SHA.
   Understand what behavior changed, not just what lines changed.

2. **Extract doc hints** — Identify keywords a developer would search for in
   documentation (e.g., "JWT expiry", "environment variables", "TokenExpiredError").
   If there are no doc-relevant keywords (pure refactors, test changes, lock files),
   stop here and output: {"action": "skipped", "reason": "no doc-relevant changes"}.

3. **Find documentation files** — Call list_repository_tree to get all files.
   Filter for .md, .rst, .mdx, openapi.yaml, openapi.json files only.

4. **Score each doc file** — For each doc file, call get_file_content and score it
   0.0–1.0 for relevance to the change. Only proceed with files scoring ≥ 0.65.

5. **Rewrite affected sections** — For each relevant doc file:
   - Read its current content (already done in step 4).
   - Rewrite ONLY the sections that reference the changed feature.
   - Do NOT change other sections, headings, or writing style.
   - Return the COMPLETE updated file content.

6. **Create a branch** — Call create_branch with name pattern: synkron/docs-{sha[:8]}

7. **Commit each updated file** — Call commit_file for each changed doc.
   Use commit messages like: "docs: update {filename} for {sha[:8]} [synkron]"

8. **Open a merge request** — Call create_merge_request with:
   - Title: "Docs: {one-sentence summary of what changed}"
   - Description: markdown summary of what was updated and why
   - End description with: "Generated by Synkron · Review and merge if accurate ✓"

## Key Rules
- NEVER modify code files. Documentation only (.md, .rst, .mdx, .yaml).
- NEVER open an MR if no documentation actually needed updating.
- Keep the developer's writing style and tone. Don't add sections unnecessarily.
- Preserve all headings, formatting, and existing content in untouched sections.
"""


def _build_agent() -> LlmAgent:
    """
    Construct the ADK agent with a real GitLab MCPToolset.
    Called lazily so no Vertex AI SDK calls happen at import.

    The MCPToolset connects to the official GitLab MCP server via stdio,
    giving the agent genuine MCP protocol access to GitLab operations.
    """
    return LlmAgent(
        name="synkron_doc_agent",
        model="gemini-2.0-flash",
        description="Autonomous documentation maintenance agent that keeps GitLab docs in sync with code",
        instruction=SYNKRON_INSTRUCTION,
        tools=[create_gitlab_mcp_toolset()],
    )


# ── Deploy to Vertex AI Agent Engine ──────────────────────────────────────
def deploy_to_agent_engine() -> str:
    """
    Deploy the Synkron ADK agent to Vertex AI Agent Engine (Reasoning Engine).
    Run this once to get the resource name, then store it in .env as
    AGENT_ENGINE_RESOURCE.

    Requires GOOGLE_CLOUD_PROJECT and GCP_REGION to be set in your .env.

    Returns:
        The full resource name string for the deployed agent.
    """
    vertexai.init(project=settings.GOOGLE_CLOUD_PROJECT, location=settings.GCP_REGION)
    agent = _build_agent()
    logger.info("Deploying Synkron agent to Vertex AI Agent Engine...")
    remote_agent = agent_engines.create(
        agent,
        requirements=[
            "google-adk>=1.5.0",
            "mcp>=1.0.0",             # MCP Python SDK — required for MCPToolset
            "httpx>=0.27.0",
            "google-cloud-aiplatform>=1.114.0",
            "google-generativeai>=0.8.0",
        ],
        display_name="Synkron Documentation Agent",
        description="Auto-updates GitLab documentation on every code push",
    )
    resource_name = remote_agent.resource_name
    logger.info(f"Agent deployed: {resource_name}")
    return resource_name


# ── Query the deployed agent ───────────────────────────────────────────────
async def run_agent(session_id: str, commit_sha: str, repo_id: int) -> dict:
    """
    Run the deployed Synkron agent for a commit via Vertex AI Agent Engine.

    Requires GOOGLE_CLOUD_PROJECT, GCP_REGION, and AGENT_ENGINE_RESOURCE
    to be set in your .env. See scripts/deploy_agent.py to deploy first.

    Args:
        session_id: Unique ID for this pipeline run (for tracing).
        commit_sha: The full commit SHA to process.
        repo_id: The GitLab project ID.

    Returns:
        Dict with 'mr_url' (or None if skipped) and 'events' list.
    """
    vertexai.init(project=settings.GOOGLE_CLOUD_PROJECT, location=settings.GCP_REGION)
    remote_app = agent_engines.get(settings.AGENT_ENGINE_RESOURCE)

    # Create a session for this run
    session = await remote_app.create_session_async(
        session_id=session_id,
        user_id="synkron-system"
    )

    # Build the user message — the agent knows what to do from its instruction
    message = (
        f"Process commit SHA '{commit_sha}' for GitLab project ID {repo_id}. "
        f"Follow your workflow: read the diff, score documentation files for relevance, "
        f"rewrite affected sections, and open a merge request if documentation needs updating."
    )

    result = {"events": [], "mr_url": None, "status": "running"}

    async for event in remote_app.stream_query_async(
        user_id="synkron-system",
        session_id=session.id,
        message=message
    ):
        event_str = str(event)
        result["events"].append(event_str)

        # Extract MR URL from agent's tool call results
        if "web_url" in event_str and "gitlab.com" in event_str:
            import re
            urls = re.findall(r'https://gitlab\.com/[^\s"\'>]+/merge_requests/\d+', event_str)
            if urls:
                result["mr_url"] = urls[0]

        if "skipped" in event_str.lower():
            result["status"] = "skipped"

    if result["mr_url"]:
        result["status"] = "completed"

    return result