import os
import re
import logging
import vertexai
from vertexai import agent_engines
from google.adk.agents import LlmAgent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types
from app.agent_builder.tools import create_gitlab_mcp_toolset
from app.config import settings

logger = logging.getLogger(__name__)


# ── Agent System Prompt ────────────────────────────────────────────────────
# Written in intent language — describes what to accomplish at each step,
# not which specific function to call. ADK injects the real MCP tool list
# from @zereight/mcp-gitlab at runtime, so the model picks the right tool
# by purpose rather than a hardcoded name.
SYNKRON_INSTRUCTION = """
You are Synkron, an autonomous documentation maintenance agent.

Your job: when a developer pushes code to GitLab, analyse what changed
and update only the documentation files that need to reflect that change.

## Your Workflow

1. **Retrieve the commit diff** — Get the full diff of changes between
   the `before` commit SHA and the `after` commit SHA. Understand what
   behaviour changed, not just what lines changed.

2. **Decide if docs need updating** — Extract keywords a developer would
   search for in documentation (e.g. "JWT expiry", "environment variables",
   "TokenExpiredError"). If there are no doc-relevant changes (pure refactors,
   test-only changes, lock-file bumps), stop here and output:
   {"action": "skipped", "reason": "no doc-relevant changes"}.

3. **Enumerate documentation files** — List all files in the repository
   recursively. Keep only .md, .rst, .mdx, openapi.yaml, openapi.json files.

4. **Score each doc file** — Read each doc file and score it 0.0–1.0 for
   relevance to this code change. Only proceed with files scoring >= 0.65.

5. **Rewrite affected sections** — For each relevant doc file:
   - Read its current content.
   - Rewrite ONLY the sections that reference the changed feature.
   - Do NOT change other sections, headings, or writing style.
   - Produce the COMPLETE updated file content (every section, not just the edit).

6. **Create a branch** — Create a new branch named:
   synkron/docs-{first 8 characters of the commit SHA}

7. **Commit each updated file** — Commit each changed documentation file
   to the new branch. Use commit messages like:
   "docs: update [filename] for [sha_first_8_chars] [synkron]"

8. **Open a merge request** — Create a merge request from the new branch to
   main with:
   - Title: "Docs: [one-sentence summary of what changed]"
   - Description: markdown summary of what was updated and why
   - End description with: "Generated by Synkron · Review and merge if accurate ✓"

## Key Rules
- NEVER modify code files. Documentation only (.md, .rst, .mdx, .yaml).
- NEVER open an MR if no documentation actually needed updating.
- Keep the developer's writing style and tone. Don't add sections unnecessarily.
- Preserve all headings, formatting, and existing content in untouched sections.
"""


def _build_agent() -> LlmAgent:
    """
    Construct the ADK agent with the real GitLab MCPToolset.
    Called lazily — no Vertex AI SDK calls happen at import time.

    The MCPToolset connects to @zereight/mcp-gitlab via stdio (npx),
    giving the agent genuine MCP protocol access to all GitLab operations.
    """
    return LlmAgent(
        name="synkron_doc_agent",
        model="gemini-3.5-flash",   # Consistent with the direct REST path
        description="Autonomous documentation maintenance agent that keeps GitLab docs in sync with code",
        instruction=SYNKRON_INSTRUCTION,
        tools=[create_gitlab_mcp_toolset()],
    )


# ── Local ADK Runner (Gemini API — no Vertex AI cost) ─────────────────────
async def run_agent(session_id: str, before_sha: str, after_sha: str, repo_id: int) -> dict:
    """
    Run the Synkron ADK agent locally using the Gemini API (zero Vertex AI cost).

    The agent uses the real @zereight/mcp-gitlab MCP server over stdio, so every
    GitLab operation (read diff, list files, commit, open MR) goes through the
    Model Context Protocol.

    Required in .env:
      GOOGLE_API_KEY=<from https://aistudio.google.com>
      GOOGLE_GENAI_USE_VERTEXAI=FALSE
      USE_AGENT_BUILDER=true

    Args:
        session_id:  Unique ID for this pipeline run (for tracing).
        before_sha:  The prior commit SHA (from webhook).
        after_sha:   The new commit SHA (from webhook).
        repo_id:     The GitLab project ID.

    Returns:
        Dict with 'mr_url', 'mr_id', 'status', and 'events'.
    """
    # Ensure ADK reads Gemini API key from environment (not Vertex AI).
    # If GOOGLE_API_KEY isn't explicitly set, fallback to GEMINI_API_KEY.
    api_key = settings.GOOGLE_API_KEY or settings.GEMINI_API_KEY
    if api_key:
        os.environ.setdefault("GOOGLE_API_KEY", api_key)
    os.environ.setdefault("GOOGLE_GENAI_USE_VERTEXAI", "FALSE")

    agent = _build_agent()
    session_service = InMemorySessionService()
    runner = Runner(
        agent=agent,
        app_name="synkron",
        session_service=session_service,
    )

    # Create a session for this pipeline run
    await session_service.create_session(
        app_name="synkron",
        user_id="synkron-system",
        session_id=session_id,
    )

    message_text = (
        f"Process changes for GitLab project ID {repo_id}. "
        f"The diff is between before_sha: '{before_sha}' and after_sha: '{after_sha}'. "
        f"Follow your workflow: retrieve the commit diff between those two SHAs, "
        f"identify which documentation files need updating (score >= 0.65), "
        f"rewrite only the affected sections, create a branch, commit each file, "
        f"and open a merge request. If no documentation needs updating, output: "
        f'{{"action": "skipped", "reason": "no doc-relevant changes"}}'
    )

    new_message = types.Content(
        role="user",
        parts=[types.Part(text=message_text)],
    )

    result = {"events": [], "mr_url": None, "mr_id": None, "status": "running"}

    async for event in runner.run_async(
        user_id="synkron-system",
        session_id=session_id,
        new_message=new_message,
    ):
        event_str = str(event)
        result["events"].append(event_str[:800])   # cap stored size

        # Extract MR URL + iid from the MCP tool response
        if "gitlab.com" in event_str and "merge_requests" in event_str:
            # URL pattern: https://gitlab.com/group/repo/-/merge_requests/42
            url_match = re.search(
                r'https://gitlab\.com/[^\s"\'<>]+/-/merge_requests/(\d+)',
                event_str
            )
            if url_match and not result["mr_url"]:
                result["mr_url"] = url_match.group(0)
                result["mr_id"] = int(url_match.group(1))

        # Also catch the iid field directly from MCP tool JSON response
        if not result["mr_id"] and '"iid"' in event_str:
            iid_match = re.search(r'"iid"\s*:\s*(\d+)', event_str)
            if iid_match:
                result["mr_id"] = int(iid_match.group(1))

        if "skipped" in event_str.lower() or "no doc-relevant" in event_str.lower():
            result["status"] = "skipped"

    if result["mr_url"]:
        result["status"] = "completed"

    return result


# ── Optional: Deploy to Vertex AI Agent Engine ─────────────────────────────
def deploy_to_agent_engine() -> str:
    """
    Deploy the Synkron ADK agent to Vertex AI Agent Engine (Reasoning Engine).
    This is entirely optional — run it once to get a resource name, then store
    it in .env as AGENT_ENGINE_RESOURCE if you want the cloud-hosted path.

    Requires GOOGLE_CLOUD_PROJECT and GCP_REGION to be set in your .env.

    Returns:
        The full resource name string for the deployed agent.
    """
    vertexai.init(project=settings.GOOGLE_CLOUD_PROJECT, location=settings.GCP_REGION)
    agent = _build_agent()
    logger.info("Deploying Synkron agent to Vertex AI Agent Engine...")
    remote_agent = agent_engines.create(
        agent,
        requirements=[
            "google-adk>=1.5.0",
            "mcp>=1.0.0",           # MCP Python SDK — required for MCPToolset
            "httpx>=0.27.0",
            "google-cloud-aiplatform>=1.114.0",
            "google-genai>=1.28.0",
        ],
        display_name="Synkron Documentation Agent",
        description="Auto-updates GitLab documentation on every code push",
    )
    resource_name = remote_agent.resource_name
    logger.info(f"Agent deployed: {resource_name}")
    return resource_name