from app.services.github import GitHubClient
from app.services.gemini import call_gemini
from typing import List
import logging

logger = logging.getLogger(__name__)


class PRCreatorAgent:
    def __init__(self, client: GitHubClient, commit_sha: str,
                 doc_updates: List[dict], analysis: dict):
        self.client      = client
        self.commit_sha  = commit_sha
        self.doc_updates = doc_updates
        self.analysis    = analysis


    async def run(self) -> dict:
        branch = f"synkron/docs-{self.commit_sha[:8]}"

        # Step 1: branch off the default branch
        await self.client.create_branch(branch)
        logger.info(f"Created branch: {branch}")

        # Step 2: commit every updated doc in ONE atomic commit.
        # The [synkron] tag is what the push webhook guard keys on to avoid looping.
        files = {u["doc_path"]: u["updated_content"] for u in self.doc_updates}
        message = f"docs: sync documentation for {self.commit_sha[:8]} [synkron]"
        await self.client.commit_files(branch, files, message)
        logger.info(f"Committed {len(files)} file(s) to {branch}")

        # Step 3: PR description via Gemini
        files_list = "\n".join(
            f"- `{u['doc_path']}` — {u['explanation']}" for u in self.doc_updates
        )
        desc_prompt = f"""Write a GitHub pull request description for a Synkron documentation update.

Triggered by commit: {self.commit_sha[:8]}
Code change: {self.analysis['summary']}
Files updated:
{files_list}

Include:
1. One paragraph: why these docs needed updating
2. Bullet list: what changed in each file
3. Final line: "Generated by Synkron · Review and merge if accurate."

Format as clean markdown. Professional and concise."""

        description = await call_gemini(desc_prompt, model="flash", temperature=0.3)

        # Step 4: open the PR
        summary_short = self.analysis["summary"][:65]
        pr = await self.client.create_pull_request(
            head_branch=branch,
            title=f"Docs: {summary_short}",
            body=description,
        )

        # Optional labels — guarded, because a label missing from the repo returns
        # 422, and a cosmetic label must never break PR creation.
        try:
            await self.client.add_labels(pr["number"], ["documentation", "synkron"])
        except Exception as e:
            logger.warning(f"Could not add labels to PR #{pr['number']}: {e}")

        logger.info(f"PR opened: {pr['url']}")
        return pr