from app.services.gitlab_mcp import GitLabMCP
from app.services.gemini import call_gemini
from typing import List
import logging

logger = logging.getLogger(__name__)


class PRCreatorAgent:
    def __init__(self, repo_id: int, commit_sha: str,
                 doc_updates: List[dict], analysis: dict):
        self.repo_id     = repo_id
        self.commit_sha  = commit_sha
        self.doc_updates = doc_updates
        self.analysis    = analysis
        self.mcp         = GitLabMCP()

    async def run(self) -> dict:
        branch = f"synkron/docs-{self.commit_sha[:8]}"

        # Step 1: Create branch via GitLab MCP
        await self.mcp.create_branch(self.repo_id, branch)
        logger.info(f"Created branch: {branch}")

        # Step 2: Commit each updated doc file via GitLab MCP
        for update in self.doc_updates:
            await self.mcp.commit_file(
                project_id=self.repo_id,
                branch=branch,
                file_path=update["doc_path"],
                content=update["updated_content"],
                message=f"docs: update {update['doc_path']} for {self.commit_sha[:8]} [synkron]"
            )
            logger.info(f"Committed: {update['doc_path']}")

        # Step 3: Generate MR description with Gemini Flash
        files_list  = "\n".join([
            f"- `{u['doc_path']}` — {u['explanation']}"
            for u in self.doc_updates
        ])
        desc_prompt = f"""Write a GitLab merge request description for a Synkron documentation update.

Triggered by commit: {self.commit_sha[:8]}
Code change: {self.analysis['summary']}
Files updated:
{files_list}

Include:
1. One paragraph: why these docs needed updating
2. Bullet list: what changed in each file
3. Final line: "Generated by Synkron · Review and merge if accurate ✓"

Format as clean markdown. Professional and concise."""

        description = await call_gemini(desc_prompt, model="flash", temperature=0.3)

        # Step 4: Open merge request via GitLab MCP
        summary_short = self.analysis["summary"][:65]
        mr = await self.mcp.create_merge_request(
            project_id=self.repo_id,
            source_branch=branch,
            title=f"Docs: {summary_short}",
            description=description
        )
        logger.info(f"MR opened: {mr['web_url']}")
        return mr